### ISSUE TITLE
Snippets not available in the IntelliJ client

### ISSUE THREAD

**Issue by wgalanciak** [CodeTogether-Inc/CodeTogether-Live#421]
**Describe the bug**
When user connects to the session using the IntelliJ client, snippets like sout, fori, etc. are not visible in the list of completion suggestions.

**To Reproduce**
1. Start a session in IntelliJ.
2. Join it from another IntelliJ instance.
3. Type `sou` and trigger content assist.
4. `sout` is not available on the list of the proposals.

**Expected behavior**
`sout` is available.

**CodeTogether Host**
 - IDE: IntelliJ

**IDE Participant**
 - IDE: IntelliJ

**Additional context**
All works fine when connect using the browser client.

**Comment by kirill-ch** [comment]
Would be nice to have snippets like “sout”, “fori”, “iter” with the same code completion as in IntelliJ IDEA.

**Comment by kirill-ch** [comment]
“psvm” snippet also is useful.
